---
- name: Install "{{ ubuntu16.zabbix_pre_packages }}" packages
  apt:
    name: "{{ ubuntu16.zabbix_pre_packages }}"
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'