---
- include_tasks: "{{ ansible_os_family }}.yml"

- name: Set up the schema and import the data into the zabbix database
  shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -u "{{ mysql_db_user }}" -p"{{ mysql_db_password }}" "{{ mysql_db_name }}"
  register: zcat_result
  failed_when: 'zcat_result|failed and "already exists" not in zcat_result.stderr'

- name: Configure zabbix_server.conf
  template:
    src: templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: 0644
  register: zabbix_server_conf_result

- name: Set timezone in apache.conf
  replace:
    path: /etc/zabbix/apache.conf
    regexp: '(^\s*)# php_value date.timezone.*/.*'
    replace: '\1php_value date.timezone Europe/Kiev'
    backup: yes
  notify:
    - restart apache

- name: Configure zabbix.conf.php
  template:
    src: templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    mode: 0644
  register: zabbix_conf_php_result

- name: Restart zabbix server
  service:
    name: "{{ zabbix_service }}"
    enabled: yes
    state: restarted
  when: zabbix_server_conf_result.changed or zabbix_conf_php_result.changed

- name: Check if zabbix-server listens to port
  shell: netstat -tulpan | grep 10051
  register: listen_result
  failed_when: listen_result.rc != 0

- debug:
    msg: "{{ listen_result.stdout }}"