---
- include_tasks: "{{ ansible_os_family }}.yml"

# - name: Configure my.cnf
#   copy: src=.roles/mysql/files/my.cnf
#         dest=/etc/mysql/my.cnf
#         owner=root
#         group=root
#         mode=0640
#   notify:
#     - restart "{{ mysql_service }}"

- name: Create database "{{ mysql_db_name }}"
  mysql_db:
    name: "{{ mysql_db_name }}"

- name: Add mysql-user
  mysql_user: name="{{ mysql_db_user }}"
              password="{{ mysql_db_password }}"
              priv="{{ mysql_db_name }}.*:ALL"

- name: Start mysql server
  service:
    name: "{{ mysql_service }}"
    enabled: yes
    state: started