---
- name: Install "{{ ubuntu16.mysql_packages }}" packages
  apt:
    name: "{{ ubuntu16.mysql_packages }}"
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'

# - name: Configure my.cnf
#   copy: src=.roles/mysql/files/my.cnf
#         dest=/etc/mysql/my.cnf
#         owner=root
#         group=root
#         mode=0640
#   notify:
#     - restart mysql

- name: Create database "{{ mysql_db_name }}"
  mysql_db:
    name: "{{ mysql_db_name }}"

- name: Add mysql-user
  mysql_user: name="{{ mysql_db_user }}"
              password="{{ mysql_db_password }}"
              priv=*.*:ALL
  notify:
    - start mysql