---
- name: Import repository key
  rpm_key:
    state: present
    key: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

- name: Install Zabbix rpm
  yum:
    name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    state: present
  register: result
  until: result|succeeded
  retries: 5
  delay: 3

- name: Install "{{ zabbix_agent }}" packages
  yum:
    name: "{{ zabbix_agent }}"

- shell: sestatus | grep -i current
  register: sestatus_result

- debug:
    msg: "{{ sestatus_result.stdout }}"

- name: Set selinux to permissive
  command: setenforce 0
  when: '"permissive" not in sestatus_result.stdout'





    